# Generated by Django 6.0.6 on 2026-06-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategory',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming Languages'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('deployment', 'Deployment'), ('tools', 'Tools')], max_length=50, unique=True),
        ),
    ]
