# Generated by Django 6.0.6 on 2026-06-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table=' Contact Messages',
        ),
    ]
